[package]
name = "imag-edit"
version = "0.9.3"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-edit command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://imag-pim.org/doc/"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
log          =  "0.4"
version      =  "3"
toml         =  "0.4"
toml-query   =  "0.8"

libimagstore     = { version = "0.9.3", path = "../../../lib/core/libimagstore" }
libimagrt        = { version = "0.9.3", path = "../../../lib/core/libimagrt" }
libimagerror     = { version = "0.9.3", path = "../../../lib/core/libimagerror" }
libimagutil      = { version = "0.9.3", path = "../../../lib/etc/libimagutil" }
libimagentryedit = { version = "0.9.3", path = "../../../lib/entry/libimagentryedit" }

[dependencies.clap]
version = "^2.29"
default-features = false
features = ["color", "suggestions", "wrap_help"]

[dev-dependencies.libimagutil]
version          = "0.9.1"
path = "../../../lib/etc/libimagutil"
default-features = false
features         = ["testing"]

[dev-dependencies.libimagrt]
version          = "0.9.1"
path             = "../../../lib/core/libimagrt"
default-features = false
features         = ["testing"]

