sudo: false
os:
  - linux

dist:
  - trusty

language: rust

matrix:
    include:
        - language: nix
          script:
            - bash ./scripts/find-dead-symlinks
            - bash ./scripts/license-headers-updated
            - bash ./scripts/branch-contains-no-tmp-commits
            - bash ./scripts/version-updated
        - language: rust
          rust: 1.32.0
          cache:
            directories:
              - /home/travis/.cargo
          before_cache:
            - rm -rf /home/travis/.cargo/registry
          script:
            - cargo build --all --all-features -j 1  || exit 1
            - cargo test  --all --all-features -j 1  || exit 1
        - language: rust
          rust: 1.33.0
          cache:
            directories:
              - /home/travis/.cargo
          before_cache:
            - rm -rf /home/travis/.cargo/registry
          script:
            - cargo build --all --all-features -j 1  || exit 1
            - cargo test  --all --all-features -j 1  || exit 1
        - language: rust
          rust: stable
          cache:
            directories:
              - /home/travis/.cargo
          before_cache:
            - rm -rf /home/travis/.cargo/registry
          script:
            - cargo build --all --all-features -j 1  || exit 1
            - cargo test  --all --all-features -j 1  || exit 1
        - language: rust
          rust: beta
          cache:
            directories:
              - /home/travis/.cargo
          before_cache:
            - rm -rf /home/travis/.cargo/registry
          script:
            - cargo build --all --all-features -j 1  || exit 1
            - cargo test  --all --all-features -j 1  || exit 1
        - language: rust
          rust: nightly
          cache:
            directories:
              - /home/travis/.cargo
          before_cache:
            - rm -rf /home/travis/.cargo/registry
          before_install:
            - curl -L https://github.com/mozilla/grcov/releases/download/v0.4.1/grcov-linux-x86_64.tar.bz2 | tar jxf -
          script:
            - export CARGO_INCREMENTAL=0
            - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
            - cargo build --verbose $CARGO_OPTIONS
            - cargo test --verbose $CARGO_OPTIONS
            - |
              zip -0 ccov.zip `find . \( -name "*imag*.gc*" \) -print`;
              ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" -o lcov.info;
              bash <(curl -s https://codecov.io/bash) -f lcov.info;


addons:
  apt:
    packages:
    - libdbus-1-dev
    - pkg-config

notifications:
  email:
    on_success: always
    on_failure: always
  irc:
    channels:
      - chat.freenode.net#imag
    template:
      - "%{repository_name} (%{branch} @ %{commit} by %{author}): %{result}"

