sudo: false
os:
  - linux

dist:
  - trusty

language: rust

matrix:
    include:
        - language: nix
          script:
            - bash ./scripts/find-dead-symlinks
            - bash ./scripts/license-headers-updated
            - bash ./scripts/branch-contains-no-tmp-commits
            - bash ./scripts/version-updated
        - language: rust
          rust: 1.27.2
          cache:
            cargo: true
          script:
            - cargo build --all --all-features -j 1  || exit 1
            - cargo test  --all --all-features -j 1  || exit 1
        - language: rust
          rust: 1.28.0
          cache:
            cargo: true
          script:
            - cargo build --all --all-features -j 1  || exit 1
            - cargo test  --all --all-features -j 1  || exit 1
        - language: rust
          rust: stable
          cache:
            cargo: true
          script:
            - cargo build --all --all-features -j 1  || exit 1
            - cargo test  --all --all-features -j 1  || exit 1


addons:
  apt:
    packages:
    - libdbus-1-dev
    - pkg-config

notifications:
  email:
    on_success: never
  irc:
    channels:
      - chat.freenode.net#imag
    template:
      - "%{repository_name} (%{branch} @ %{commit} by %{author}): %{result}"

